apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    nodejs-welcome:
      repositories:
        - owner: ujjinimech
          names:
            - argo-1
            - nodejs-welcome  
      webhook:
        endpoint: /nodejs-welcome
        port: "12000"
        method: POST
        url: https://65.108.94.30:31326
      events:
        - "*"
      apiToken:    
        name: github-access
        key: token

      insecure: true
      # Determines if notifications are sent when the webhook is triggered
      active: true
      # The media type used to serialize the payloads
      contentType: json
