apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/sathyap0104
          name: sathyap0104
        - mountPath: /secret
          name: sshkey
        - mountPath: /etc/ssh
          name: known-hosts
    volumes:
      - name: sathyap0104
        emptyDir: {}
      - name: sshkey
        secret:
          secretName: git-ssh
      - name: known-hosts
        secret:
          secretName: git-known-hosts
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "git@github.com:argoproj/argo-workflows.git"
              cloneDirectory: "/git/argoproj"
              sshKeyPath: "/secret/key"
              namespace: argo-events
              filePath: "examples/hello-world.yaml"
              branch: "master"