apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/ujjinimech
          name: ujjinimech
        - mountPath: /secret
          name: sshkey
    volumes:
      - name: ujjinimech
        emptyDir: {}
      - name: sshkey
        secret:
          secretName: git-ssh
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: nodejs-welcome
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "git@github.com:ujjinimech/argo-1.git"
              cloneDirectory: "/git/argo-1"
              sshKeyPath: "/secret/key"
              namespace: argo-events
              filePath: "argo-workflow/kaniko-workflow.yaml"
              branch: "master"
