apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        values:
          replicaCount: '2'
          image.tag: '1.0.0'
      - cluster: hyd
        url: https://vc-slovgncdugkndjcvlemy.zlr-dc1.apps.dev.klusternetes.com
        values:
          replicaCount: '3'
          image.tag: '1.0.0'
      - cluster: mumbai
        url: https://vc-cj9ris5rz36w1gm7khce.zlr-dc1.apps.dev.klusternetes.com
        values:
          replicaCount: '4'
          image.tag: '1.0.0'
  template:
    metadata:
      name: '{{cluster}}-test'
    spec:
      project: default
      source:
        repoURL: https://github.com/sai8465/helmchart.git
        targetRevision: HEAD
        path: angular
        helm:
          parameters:
          - name: replicaCount
            value: '{{values.replicaCount}}'
          - name: image.tag
            value: '{{values.image.tag}}'
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
